name: MERN CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install server dependencies
        working-directory: ./backend
        run: npm install

      - name: Run server tests
        working-directory: ./backend
        run: npm test --if-present

      - name: Install client dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run client build
        working-directory: ./frontend
        run: npm run build
